name: build

on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [3.7, 3.8]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.0
      with:
          access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.version }}
        conda-channels: anaconda
    - run: conda --version
    - run: which python
    - run: conda install mpi4py h5py pytorch torchvision cpuonly -c pytorch -c conda-forge

    - name: Install the package
      run: pip install .[test,hpc]
      env:
        CONDA_PREFIX: /usr/share/miniconda

    - name: Test with pytest
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: |
        pytest tests --cov-config setup.cfg

    - name: Test with multithreading
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: |
        pytest horovod_tests -n 2 --cov-config setup.cfg

    - name: Coveralls Parallel
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COVERALLS_FLAG_NAME: python-${{ matrix.version }}
        COVERALLS_PARALLEL: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
