name: build

on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [3.8]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.0
      with:
          access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.version }}
        conda-channels: anaconda
    - name: Install essential
      run: |
        sudo apt update
        sudo apt install build-essential

    - name: Install conda packages
      run: |
        conda install -c anaconda cmake
        conda install mpi4py h5py pytorch torchvision cpuonly -c pytorch -c conda-forge
        conda install -c conda-forge libstdcxx-ng
        conda install -c anaconda gxx_linux-64
    - name: Instal pip packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install packaging
        pip3 install setuptools==66.0.0
    - name: Install horovod
      env:
        HOROVOD_WITHOUT_TENSORFLOW: 1
        HOROVOD_WITHOUT_MXNET: 1
        HOROVOD_WITHOUT_GLOO: 1
      run: python -m pip install  --use-pep517 horovod

    - name: Install the package
      run: python -m pip install .[test]
      env:
        CONDA_PREFIX: /usr/share/miniconda

    - name: Test with multithreading
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: mpirun -np 2 coverage run -m pytest tests_hvd

    - name: Test with single thread
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: coverage run -m pytest tests

    - name: Combine all coverage results
      run: coverage combine

    - run: coverage report

    - name: Coveralls Parallel
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COVERALLS_FLAG_NAME: python-${{ matrix.version }}
        COVERALLS_PARALLEL: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
