name: build

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['3.9']

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.0
      with:
          access_token: ${{ github.token }}
    - uses: actions/checkout@v4
    # - name: Setup conda
    #   uses: conda-incubator/setup-miniconda@v3
    #   with:
    #     auto-update-conda: true
    #     python-version: ${{ matrix.version }}
    #     channels: anaconda
    - name: Install essential
      run: |
        sudo apt update
        sudo apt install build-essential pandoc
    # - name: Install conda packages
    #   run: |
    #     conda install -c anaconda cmake
    #     conda install rdkit mpi4py h5py pytorch==2.1.1 cpuonly -c pytorch -c conda-forge
    #     conda install -c conda-forge libstdcxx-ng
    #     conda install -c anaconda gxx_linux-64

    - name: Install the package
      run: python -m pip install .[test,doc]
      env:
        CONDA_PREFIX: /usr/share/miniconda

    # - name: Test with multithreading
    #   env:
    #     CONDA_PREFIX: /usr/share/miniconda
    #   run: mpirun -np 2 coverage run -m pytest tests_hvd

    - name: Test with single thread
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: coverage run -m pytest tests

    - name: Combine all coverage results
      run: coverage combine

    - run: coverage report

    - name: Coveralls Parallel
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COVERALLS_FLAG_NAME: python-${{ matrix.version }}
        COVERALLS_PARALLEL: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
