name: build

on:
  push:
    branches:
      - master
      - main
      - development
  pull_request:
    branches:
      - master
      - main
      - development

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        version: ['3.9']

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.0
      with:
          access_token: ${{ github.token }}
    - uses: actions/checkout@v4
    - name: Install essential
      run: |
        sudo apt update
        sudo apt install build-essential pandoc
    - name: Install specific packages
      run: |
        python -m pip install torch==2.4.1 --index-url https://download.pytorch.org/whl/cpu
    - name: Install the package
      run: python -m pip install .[test,doc]
      env:
        CONDA_PREFIX: /usr/share/miniconda

    - name: Test with single thread
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: coverage run -m pytest tests

    - name: Combine all coverage results
      run: coverage combine

    - run: coverage report

    - name: Coveralls Parallel
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COVERALLS_FLAG_NAME: python-${{ matrix.version }}
        COVERALLS_PARALLEL: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
